# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import app_pb2 as app__pb2


class AppStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunInference = channel.unary_unary(
                '/App/RunInference',
                request_serializer=app__pb2.InferenceRequest.SerializeToString,
                response_deserializer=app__pb2.InferenceResponse.FromString,
                )
        self.RunTraining = channel.unary_unary(
                '/App/RunTraining',
                request_serializer=app__pb2.TrainRequest.SerializeToString,
                response_deserializer=app__pb2.TrainResponse.FromString,
                )


class AppServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunInference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunTraining(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunInference': grpc.unary_unary_rpc_method_handler(
                    servicer.RunInference,
                    request_deserializer=app__pb2.InferenceRequest.FromString,
                    response_serializer=app__pb2.InferenceResponse.SerializeToString,
            ),
            'RunTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.RunTraining,
                    request_deserializer=app__pb2.TrainRequest.FromString,
                    response_serializer=app__pb2.TrainResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'App', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class App(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/App/RunInference',
            app__pb2.InferenceRequest.SerializeToString,
            app__pb2.InferenceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/App/RunTraining',
            app__pb2.TrainRequest.SerializeToString,
            app__pb2.TrainResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
