server {
    listen 8080;
    client_max_body_size 2g;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    location ~ ^/(api/|static/|admin|django-rq) {
        proxy_pass http://server:8080;
    }
    location / {
        proxy_pass http://ui:8000;
    }
}
