---
version: 1
name: Segmentation Spleen
description: MONAI Label App to provide active learning solution to label Spleen Organ over 3D CT Images
dimension: 3
labels:
  - spleen
config:
  device: cuda
  train:
    name: model_01
    device: cuda
    amp: false
    lr: 0.0001
    epochs: 1
    network:
      UNet: UNet with channels (16, 32, 64, 128, 256)
      BasicUNet: Basic UNet with features (16, 32, 64, 128, 256)
  activelearning:
    strategy:
      random: Use Random Strategy to get Next Sample # default
      first: Pick first available Sample (ordered by name)
      last: Pick last available Sample (ordered by name)
