---
version: 1
name: Segmentation Spleen
description: MONAI Label App to provide active learning solution to label Spleen Organ over 3D CT Images
dimension: 3
config:
  infer:
    device: cuda
  train:
    name: model_01
    pretrained: true
    device: cuda
    amp: true
    lr: 0.0001
    epochs: 50
    val_split: 0.2
    train_batch_size: 1
    val_batch_size: 1
