---
version: 1
name: Segmentation Heart
description: MONAI Label App to provide active learning solution to label heart over 3D MRI Images
dimension: 3
labels:
  - heart
config:
  infer:
    device: cuda
  train:
    name: model_01
    device: cuda
    amp: true
    lr: 0.0001
    epochs: 5
  activelearning:
    strategy:
      random: Use Random Strategy to get Next Sample # default
      first: Pick first available Sample (ordered by name)
      last: Pick last available Sample (ordered by name)
