---
version: 1
name: DeepEdit - Brain Ventricle
description: MONAI Label App to provide active learning solution using DeepEdit to label brain ventricle over 3D MRI Images
dimension: 3
labels:
  - brain ventricle
config:
  infer:
    device: cuda
  train:
    name: model_01
    pretrained: False
    device: cuda
    amp: true
    lr: 0.0001
    epochs: 100
    val_split: 0.2
    train_batch_size: 1
    val_batch_size: 1
