# Copyright (c) MONAI Consortium
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

trigger: none
pr: none

stages:
  - stage: 'Build'
    jobs:
      - job: Tests
        timeoutInMinutes: 60
        pool: "Monai VMSS"
        # container:
        #   image: nvcr.io/nvidia/pytorch:22.03-py3
        #   options: --gpus all
        steps:
          - script: |
              sudo killall apt apt-get | echo killing existing apt
              sudo rm -rf /var/lib/apt/lists/lock
              sudo rm -rf /var/cache/apt/archives/lock
              sudo rm -rf /var/lib/dpkg/lock
              sudo dpkg --configure -a
              sudo apt-get update --fix-missing -y
              sudo apt-get install -f -y
            displayName: 'Fix Lock (Hack)'
          - bash: |
              sudo apt update
              sudo apt-get install python3-pip python-is-python3 openslide-tools -y
              python -m pip install --user --upgrade pip setuptools wheel
              python -m pip install -r requirements-dev.txt
              python -m pip install pytest-azurepipelines
            displayName: 'Install dependencies'
          - bash: $(pwd)/runtests.sh --clean
            displayName: 'Clean'
          - bash: python -m pre_commit run --all-files
            displayName: 'PreCommit'
          - bash: $(pwd)/runtests.sh --unittests
            displayName: 'Unit tests'
          - task: UseDotNet@2
            displayName: 'Use .NET Core sdk'
            inputs:
              packageType: sdk
              version: 3.1.x
              installationPath: $(Agent.ToolsDirectory)/dotnet
          - task: PublishTestResults@2
            condition: succeededOrFailed()
            inputs:
              testResultsFiles: '**/test-*.xml'
              testRunTitle: 'Publish test results for Python $(python.version)'
            displayName: 'Publish Test Results'
          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
            displayName: 'Publish Code Coverage Results'

      - job: Package
        timeoutInMinutes: 30
        pool: "Monai VMSS"
        # container:
        #   image: nvcr.io/nvidia/pytorch:22.03-py3
        #   options: --gpus all
        steps:
          - script: |
              sudo killall apt apt-get | echo killing existing apt
              sudo rm -rf /var/lib/apt/lists/lock
              sudo rm -rf /var/cache/apt/archives/lock
              sudo rm -rf /var/lib/dpkg/lock
              sudo dpkg --configure -a
              sudo apt-get update --fix-missing -y
              sudo apt-get install -f -y
            displayName: 'Fix Lock (Hack)'
          - bash: |
              sudo apt update
              sudo apt-get install python3-pip python-is-python3 openslide-tools -y
              python -m pip install --user --upgrade pip setuptools wheel

              sudo ./plugins/ohif/requirements.sh
            displayName: 'Install dependencies'
          - bash: |
              ./runtests.sh --clean
              BUILD_OHIF=true python setup.py sdist bdist_wheel
              ls -l dist
              rm -r build monailabel*.egg-info
            displayName: 'Build Package'
          - bash: |
              tmp_dir=$(mktemp -d)
              cp dist/monailabel* "$tmp_dir"

              # install from wheel
              python -m pip install "$tmp_dir"/monailabel*.whl
              python -m pip show monailabel
              python -c 'import monailabel; monailabel.print_config()' 2>&1 | grep -iv "unknown"
              python -c 'import monailabel; print(monailabel.__file__)'

              # check
              export PATH=$PATH:/home/AzDevOps/.local/bin
              echo MONAILabel Path: `which monailabel`
              monailabel apps

              # integration test
              python -m pip install pytest
              ./runtests.sh --net

              # cleanup
              python -m pip uninstall -y monailabel
              rm -r "$tmp_dir"
            displayName: 'Verify (wheel) Package + Integration Tests'

      - job: Docker
        timeoutInMinutes: 30
        pool: "Monai VMSS"
        steps:
          - script: |
              sudo killall apt apt-get | echo killing existing apt
              sudo rm -rf /var/lib/apt/lists/lock
              sudo rm -rf /var/cache/apt/archives/lock
              sudo rm -rf /var/lib/dpkg/lock
              sudo dpkg --configure -a
              sudo apt-get update --fix-missing -y
              sudo apt-get install -f -y
            displayName: 'Fix Lock (Hack)'
          - bash: |
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
              sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
              sudo apt-get update
              sudo apt-get install docker-ce
            displayName: 'Install dependencies'
          - bash: |
              ./runtests.sh --clean
              docker system prune -f
              DOCKER_BUILDKIT=1 docker build -t projectmonai/monailabel:latest -f Dockerfile .
            displayName: 'Build Latest Docker'
          - bash: |
              ./runtests.sh --clean
              docker run --gpus all --rm -i --ipc=host --net=host -v $(pwd):/workspace projectmonai/monailabel:latest /workspace/runtests.sh --net
            displayName: 'Verify Latest Docker'
