trigger: none
pr: none

stages:
  - stage: 'Build'
    jobs:
      - job: Tests
        timeoutInMinutes: 60
        pool: "Monai VMSS"
        #container: projectmonai/monai:latest
        steps:
          - script: |
              sudo killall apt apt-get | echo killing existing apt
              sudo rm -rf /var/lib/apt/lists/lock
              sudo rm -rf /var/cache/apt/archives/lock
              sudo rm -rf /var/lib/dpkg/lock
              sudo dpkg --configure -a
              sudo apt-get update --fix-missing -y
              sudo apt-get install -f -y
              sudo apt update && sudo apt install -y python3-pip python-is-python3
              sudo apt-get install openslide-tools -y
              python3 -m pip install --upgrade pip wheel
              python3 -m pip install -r requirements-dev.txt
              python3 -m pip install pytest-azurepipelines
            displayName: 'Install dependencies'
          - bash: $(pwd)/runtests.sh --clean
            displayName: 'Clean'
          - bash: python3 -m pre_commit run --all-files
            displayName: 'PreCommit'
          - bash: $(pwd)/runtests.sh --unittests
            displayName: 'Unit tests'
          - task: UseDotNet@2
            displayName: 'Use .NET Core sdk'
            inputs:
              packageType: sdk
              version: 3.1.x
              installationPath: $(Agent.ToolsDirectory)/dotnet
          - task: PublishTestResults@2
            condition: succeededOrFailed()
            inputs:
              testResultsFiles: '**/test-*.xml'
              testRunTitle: 'Publish test results for Python $(python.version)'
            displayName: 'Publish Test Results'
          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
            displayName: 'Publish Code Coverage Results'

      - job: Package
        timeoutInMinutes: 30
        pool: "Monai VMSS"
        #container: projectmonai/monai:latest
        steps:
          - script: |
              sudo killall apt apt-get | echo killing existing apt
              sudo rm -rf /var/lib/apt/lists/lock
              sudo rm -rf /var/cache/apt/archives/lock
              sudo rm -rf /var/lib/dpkg/lock
              sudo dpkg --configure -a
              sudo apt-get update --fix-missing -y
              sudo apt-get install -f -y
              sudo apt update && sudo apt install -y python3-pip python-is-python3 npm
              sudo apt-get install openslide-tools -y
              sudo npm install --global yarn
              python3 -m pip install --user --upgrade pip setuptools wheel
              python3 -m pip install torch>=1.7 torchvision
            displayName: 'Install dependencies'
          - script: |
              python setup.py sdist bdist_wheel
            displayName: 'Build Package'
          - script: |
              tmp_dir=$(mktemp -d)
              cp dist/monailabel* "$tmp_dir"
              rm -r build monailabel*.egg-info

              # install from tar.gz
              python -m pip install "$tmp_dir"/monailabel*.tar.gz
              python -c 'import monailabel; monailabel.print_config()' 2>&1 | grep -iv "unknown"
              python -c 'import monailabel; print(monailabel.__file__)'
              python -m pip uninstall -y monailabel

              # install from wheel
              python -m pip install "$tmp_dir"/monailabel*.whl
              python -c 'import monailabel; monailabel.print_config()' 2>&1 | grep -iv "unknown"
              python -c 'import monailabel; print(monailabel.__file__)'

              # install test utilities
              python -m pip install pytest

              # start the monailabel server in the background and run the integration tests
              ./runtests.sh --net

              # cleanup
              python -m pip uninstall -y monailabel
              rm -r "$tmp_dir"
            displayName: 'Verify Package'
