trigger: none
pr: none

stages:
  - stage: 'Test'
    jobs:
      - job: RunTests
        pool: "Monai VMSS"
        strategy:
          matrix:
            Python3.8:
              python.version: '3.8'
          maxParallel: 2
        steps:
          - script: |
              sudo apt update && sudo apt install -y python3-pip python-is-python3
              python3 -m pip install --upgrade pip wheel
              python3 -m pip install -r requirements-dev.txt
              python3 -m pip install pytest-azurepipelines
            displayName: 'Install dependencies'
          - bash: $(pwd)/runtests.sh --clean
            displayName: 'Clean'
          - bash: $(pwd)/runtests.sh --isort
            displayName: 'iSort'
          - bash: $(pwd)/runtests.sh --black
            displayName: 'Black'
          - script: $(pwd)/runtests.sh --flake8
            displayName: 'Flake8'
          - bash: echo $(pwd)/runtests.sh --pytype
            displayName: 'PyType'
          - bash: $(pwd)/runtests.sh --mypy
            displayName: 'MyPy'
          - bash: $(pwd)/runtests.sh --unittests --coverage
            displayName: 'Unit tests'
          - task: UseDotNet@2
            displayName: 'Use .NET Core sdk'
            inputs:
              packageType: sdk
              version: 3.1.x
              installationPath: $(Agent.ToolsDirectory)/dotnet
          - task: PublishTestResults@2
            condition: succeededOrFailed()
            inputs:
              testResultsFiles: '**/test-*.xml'
              testRunTitle: 'Publish test results for Python $(python.version)'
            displayName: 'Publish Test Results'
          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
            displayName: 'Publish Code Coverage Results'
