---
version: 1
name: heart_app
description: MONAI Label App to provide active learning solution to label heart over 3D MR Images
dimension: 3
labels:
  - heart
models:
  segmentation_heart:
    description: A pre-trained model for volumetric (3D) segmentation of the heart from heart image
    type: segmentation
    dimension: 3
  deepgrow_2d:
    description: A pre-trained 2D DeepGrow model based on UNET
    type: deepgrow
    dimension: 2
  deepgrow_3d:
    description: A pre-trained 3D DeepGrow model based on UNET
    type: deepgrow
    dimension: 3
  my_model:
    description: My model which is trained that got trained periodically using Active Learning solution
    type: segmentation
config:
  device: cuda
  train:
    name: model_01
    device: cuda
    amp: false
    lr: 0.0001
    epochs: 1
    network:
      UNet: UNet with channels (16, 32, 64, 128, 256) # default
      BasicUNet: Basic UNet with features (16, 32, 64, 128, 256)
  activelearning:
    strategy:
      random: Use Random Strategy to get Next Sample # default
      first: Pick first available Sample (ordered by name)
      last: Pick last available Sample (ordered by name)
      unk: I Don't know yet
