---
version: 1
name: Segmentation heart ventricles
description: MONAI Label App to provide active learning solution to label two heart chambers over 3D MR (SAX) Images
dimension: 3
labels:
  - left ventricular volume
  - left ventricle wall
  - right ventricle of heart
config:
  infer:
    device: cuda
  train:
    name: model_01
    pretrained: False
    device: cuda
    amp: true
    lr: 0.0001
    epochs: 500
    val_split: 0.1
    train_batch_size: 1
    val_batch_size: 1
