---
version: 1
name: Brain Parcelation using Highresnet 3D
description: MONAI Label App using highresnet 3D over 3D MR Images
dimension: 3
labels:
  - brain parcelation
config:
  infer:
    device: cuda
  train:
    name: model_01
    pretrained: True
    device: cuda
    amp: true
    lr: 0.0001
    epochs: 100
    val_split: 0.2
    train_batch_size: 1
    val_batch_size: 1
