---
version: 1
name: DeepEdit - Lung
description: MONAI Label App to provide active learning solution using DeepEdit to label lung over 3D CT Images
dimension: 3
labels:
  - lung
config:
  infer:
    device: cuda
  train:
    name: model_01
    device: cuda
    amp: true
    lr: 0.0001
    epochs: 50
    val_split: 0.2
