---
version: 1
name: Segmentation Left Atrium
description: MONAI Label App to provide active learning solution to label left atrium over 3D MRI Images
dimension: 3
config:
  infer:
    device: cuda
  train:
    name: model_01
    pretrained: false
    device: cuda
    amp: true
    lr: 0.0001
    epochs: 500
    val_split: 0.2
    train_batch_size: 1
    val_batch_size: 1
