---
version: 1
name: Deepgrow - Left Atrium
description: MONAI Label App to provide active learning solution using DeepGrow to label left atrium for 3D MRI Volumes
dimension: 3
labels:
  - left atrium
config:
  infer:
    device: cuda
  train:
    model:
      all: Train all Deepgrow models
      deepgrow_2d: Train deepgrow 2d model
      deepgrow_3d: Train deepgrow 3d model
    name: model_01
    device: cuda
    amp: true
    lr: 0.0001
    epochs: 50
    val_split: 0.2
