# Copyright (c) MONAI Consortium
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: monailabel-dicom
services:
  orthanc:
    image: orthancteam/orthanc@sha256:1ca07ad4a70f67f815e55a558e76718d572ed9d0571268a3fbc1516a9155c5ca
    restart: unless-stopped
    ports:
      - "127.0.0.1:8042:8042"
      - "127.0.0.1:4242:4242"
    environment:
      ORTHANC__NAME: MONAI Label local research data
      ORTHANC__REMOTE_ACCESS_ALLOWED: "true"
      ORTHANC__AUTHENTICATION_ENABLED: "false"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__DICOM_WEB__ENABLE: "true"
      ORTHANC__DICOM_WEB__ROOT: /dicom-web/
      ORTHANC__DICOM_WEB__STUDIES_METADATA: Full
      ORTHANC__DICOM_WEB__SERIES_METADATA: Full
    volumes:
      - orthanc-data:/var/lib/orthanc/db
volumes:
  orthanc-data:
